name: Build and Publish to NPM Packages

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'


jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: ðŸ” Detect changed projects
        id: changed
        run: |
          git diff --quiet HEAD^ HEAD ./package || echo "package_changed=true" >> $GITHUB_OUTPUT

      - name: Set up Node.js for npm
        uses: actions/setup-node@v3
        if: steps.changed.outputs.package_changed == 'true'
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.changed.outputs.package_changed == 'true'
        run: npm run pkg:preinstall

      - name: Publish to npm
        if: steps.changed.outputs.package_changed == 'true'
        run: npm run pkg:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Set up Node.js for GitHub Packages
        uses: actions/setup-node@v3
        if: steps.changed.outputs.package_changed == 'true'
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages
        if: steps.changed.outputs.package_changed == 'true'
        run: npm publish --registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          publish: 'npx changeset publish'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
