name: Build and Publish to npm

on:
  push:
    branches:
      - main
      
      
      
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: ðŸ” Detect changed projects
        id: changed
        run: |
              git diff --quiet HEAD^ HEAD ./package || echo "package_changed=true" >> $GITHUB_OUTPUT
      

      - name: Set up Node.js
        uses: actions/setup-node@v3
        if: steps.changed.outputs.package_changed == 'true'
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.changed.outputs.package_changed == 'true'
        run: npm run pkg:preinstall

      # - name: Build with TypeScript
      #   run: cd package && npm run build

      - name: Build with TypeScript and Publish to npm
        if: steps.changed.outputs.package_changed == 'true' && github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm run pkg:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
